# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './field_pyculator_dialog.ui'
#
# Created: Thu Apr  3 20:34:43 2014
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FieldPyculatorDialog(object):
    def setupUi(self, FieldPyculatorDialog):
        FieldPyculatorDialog.setObjectName(_fromUtf8("FieldPyculatorDialog"))
        FieldPyculatorDialog.resize(525, 596)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FieldPyculatorDialog.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(FieldPyculatorDialog)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbUpdateField = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbUpdateField.sizePolicy().hasHeightForWidth())
        self.cmbUpdateField.setSizePolicy(sizePolicy)
        self.cmbUpdateField.setObjectName(_fromUtf8("cmbUpdateField"))
        self.gridLayout.addWidget(self.cmbUpdateField, 1, 1, 1, 2)
        self.labelUpdateField = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUpdateField.sizePolicy().hasHeightForWidth())
        self.labelUpdateField.setSizePolicy(sizePolicy)
        self.labelUpdateField.setTextFormat(QtCore.Qt.PlainText)
        self.labelUpdateField.setScaledContents(False)
        self.labelUpdateField.setObjectName(_fromUtf8("labelUpdateField"))
        self.gridLayout.addWidget(self.labelUpdateField, 1, 0, 1, 1)
        self.labelLayer = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLayer.sizePolicy().hasHeightForWidth())
        self.labelLayer.setSizePolicy(sizePolicy)
        self.labelLayer.setObjectName(_fromUtf8("labelLayer"))
        self.gridLayout.addWidget(self.labelLayer, 0, 0, 1, 1)
        self.grpGlobalExpression = QtGui.QGroupBox(self.centralwidget)
        self.grpGlobalExpression.setMaximumSize(QtCore.QSize(16777215, 210))
        self.grpGlobalExpression.setCheckable(True)
        self.grpGlobalExpression.setChecked(False)
        self.grpGlobalExpression.setObjectName(_fromUtf8("grpGlobalExpression"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.grpGlobalExpression)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.txtGlobalExp = PythonEditBox(self.grpGlobalExpression)
        self.txtGlobalExp.setObjectName(_fromUtf8("txtGlobalExp"))
        self.verticalLayout_2.addWidget(self.txtGlobalExp)
        self.gridLayout.addWidget(self.grpGlobalExpression, 3, 0, 1, 3)
        self.grpFieldExpression = QtGui.QGroupBox(self.centralwidget)
        self.grpFieldExpression.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grpFieldExpression.setCheckable(False)
        self.grpFieldExpression.setObjectName(_fromUtf8("grpFieldExpression"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grpFieldExpression)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.txtFieldExp = PythonEditBox(self.grpFieldExpression)
        self.txtFieldExp.setObjectName(_fromUtf8("txtFieldExp"))
        self.verticalLayout.addWidget(self.txtFieldExp)
        self.gridLayout.addWidget(self.grpFieldExpression, 5, 0, 1, 3)
        self.grpFields = QtGui.QGroupBox(self.centralwidget)
        self.grpFields.setMaximumSize(QtCore.QSize(16777215, 170))
        self.grpFields.setObjectName(_fromUtf8("grpFields"))
        self.gridLayout_2 = QtGui.QGridLayout(self.grpFields)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnGetAll = QtGui.QPushButton(self.grpFields)
        self.btnGetAll.setObjectName(_fromUtf8("btnGetAll"))
        self.gridLayout_2.addWidget(self.btnGetAll, 3, 7, 1, 1)
        self.btnId = QtGui.QPushButton(self.grpFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnId.sizePolicy().hasHeightForWidth())
        self.btnId.setSizePolicy(sizePolicy)
        self.btnId.setObjectName(_fromUtf8("btnId"))
        self.gridLayout_2.addWidget(self.btnId, 3, 4, 1, 1)
        self.lstValues = QtGui.QListWidget(self.grpFields)
        self.lstValues.setObjectName(_fromUtf8("lstValues"))
        self.gridLayout_2.addWidget(self.lstValues, 2, 4, 1, 4)
        self.labelFields = QtGui.QLabel(self.grpFields)
        self.labelFields.setObjectName(_fromUtf8("labelFields"))
        self.gridLayout_2.addWidget(self.labelFields, 0, 1, 1, 3)
        self.lstFields = QtGui.QListWidget(self.grpFields)
        self.lstFields.setObjectName(_fromUtf8("lstFields"))
        self.gridLayout_2.addWidget(self.lstFields, 2, 1, 2, 3)
        self.labelValues = QtGui.QLabel(self.grpFields)
        self.labelValues.setObjectName(_fromUtf8("labelValues"))
        self.gridLayout_2.addWidget(self.labelValues, 0, 4, 1, 1)
        self.btnGeom = QtGui.QPushButton(self.grpFields)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGeom.sizePolicy().hasHeightForWidth())
        self.btnGeom.setSizePolicy(sizePolicy)
        self.btnGeom.setObjectName(_fromUtf8("btnGeom"))
        self.gridLayout_2.addWidget(self.btnGeom, 3, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 6, 1, 1)
        self.gridLayout.addWidget(self.grpFields, 4, 0, 1, 3)
        self.chkOnlySelected = QtGui.QCheckBox(self.centralwidget)
        self.chkOnlySelected.setObjectName(_fromUtf8("chkOnlySelected"))
        self.gridLayout.addWidget(self.chkOnlySelected, 2, 0, 1, 2)
        self.btnRun = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRun.sizePolicy().hasHeightForWidth())
        self.btnRun.setSizePolicy(sizePolicy)
        self.btnRun.setObjectName(_fromUtf8("btnRun"))
        self.gridLayout.addWidget(self.btnRun, 9, 2, 1, 1)
        self.prgTotal = QtGui.QProgressBar(self.centralwidget)
        self.prgTotal.setProperty("value", 0)
        self.prgTotal.setObjectName(_fromUtf8("prgTotal"))
        self.gridLayout.addWidget(self.prgTotal, 9, 0, 1, 2)
        self.lblLayerName = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblLayerName.sizePolicy().hasHeightForWidth())
        self.lblLayerName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLayerName.setFont(font)
        self.lblLayerName.setObjectName(_fromUtf8("lblLayerName"))
        self.gridLayout.addWidget(self.lblLayerName, 0, 1, 1, 2)
        FieldPyculatorDialog.setCentralWidget(self.centralwidget)
        self.mainToolBar = QtGui.QToolBar(FieldPyculatorDialog)
        self.mainToolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.mainToolBar.setMovable(True)
        self.mainToolBar.setIconSize(QtCore.QSize(24, 24))
        self.mainToolBar.setFloatable(True)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        FieldPyculatorDialog.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.action_open = QtGui.QAction(FieldPyculatorDialog)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_save = QtGui.QAction(FieldPyculatorDialog)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_save_as = QtGui.QAction(FieldPyculatorDialog)
        self.action_save_as.setObjectName(_fromUtf8("action_save_as"))
        self.mainToolBar.addAction(self.action_open)
        self.mainToolBar.addAction(self.action_save)
        self.mainToolBar.addAction(self.action_save_as)

        self.retranslateUi(FieldPyculatorDialog)
        QtCore.QObject.connect(self.grpGlobalExpression, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.txtGlobalExp.setVisible)
        QtCore.QMetaObject.connectSlotsByName(FieldPyculatorDialog)

    def retranslateUi(self, FieldPyculatorDialog):
        FieldPyculatorDialog.setWindowTitle(_translate("FieldPyculatorDialog", "FieldPyculator", None))
        self.labelUpdateField.setText(_translate("FieldPyculatorDialog", "Update field:", None))
        self.labelLayer.setText(_translate("FieldPyculatorDialog", "Layer:", None))
        self.grpGlobalExpression.setTitle(_translate("FieldPyculatorDialog", "Global expression", None))
        self.grpFieldExpression.setTitle(_translate("FieldPyculatorDialog", "Field expression", None))
        self.grpFields.setTitle(_translate("FieldPyculatorDialog", "Existing fields and vars", None))
        self.btnGetAll.setText(_translate("FieldPyculatorDialog", "Get all", None))
        self.btnId.setText(_translate("FieldPyculatorDialog", "$id", None))
        self.labelFields.setText(_translate("FieldPyculatorDialog", "Fields", None))
        self.lstFields.setSortingEnabled(False)
        self.labelValues.setText(_translate("FieldPyculatorDialog", "Values", None))
        self.btnGeom.setText(_translate("FieldPyculatorDialog", "$geom", None))
        self.chkOnlySelected.setText(_translate("FieldPyculatorDialog", "Update only selected features", None))
        self.btnRun.setText(_translate("FieldPyculatorDialog", "Run", None))
        self.btnRun.setShortcut(_translate("FieldPyculatorDialog", "F5", None))
        self.lblLayerName.setText(_translate("FieldPyculatorDialog", "LayerName", None))
        self.mainToolBar.setWindowTitle(_translate("FieldPyculatorDialog", "Main toolbar", None))
        self.action_open.setText(_translate("FieldPyculatorDialog", "Open", None))
        self.action_open.setToolTip(_translate("FieldPyculatorDialog", "Open file with code", None))
        self.action_open.setShortcut(_translate("FieldPyculatorDialog", "Ctrl+O", None))
        self.action_save.setText(_translate("FieldPyculatorDialog", "Save", None))
        self.action_save.setToolTip(_translate("FieldPyculatorDialog", "Save code to file", None))
        self.action_save.setShortcut(_translate("FieldPyculatorDialog", "Ctrl+S", None))
        self.action_save_as.setText(_translate("FieldPyculatorDialog", "Save as...", None))
        self.action_save_as.setToolTip(_translate("FieldPyculatorDialog", "Save code to file", None))
        self.action_save_as.setShortcut(_translate("FieldPyculatorDialog", "Ctrl+Shift+S", None))

from python_edit_box_factory import PythonEditBox
